version: 0.0
os: linux
files:
  - source: scripts/index.html
    destination: /var/www/html 
hooks:
  BeforeInstall:
    - location: scripts/nginx_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
